services:
  franka_follower_controllers:
    image: franka_follower_controllers:${ROS_DISTRIBUTION:-jazzy}
    build:
      target: application
      args:
        # Make sure that the selected franka_ros2 version is compatible with the selected ROS distribution.
        # See the following links for more information:
        #     - https://frankarobotics.github.io/docs/franka_ros2/franka_ros2/doc/compatibility_matrix.html
        #     - https://frankarobotics.github.io/docs/compatibility.html
        - ROS_DISTRIBUTION=${ROS_DISTRIBUTION:-jazzy}
        - FRANKA_ROS2_VERSION=${FRANKA_ROS2_VERSION:-v3.4.0}
    volumes:
      - type: bind
        source: ${CONFIG_FILE:-./config/gello_joint_follower.yaml}
        target: /config.yml
    privileged: true
    network_mode: host
    cap_add:
      - SYS_NICE
      - NET_ADMIN
    ulimits:
      rtprio:
        soft: 99
        hard: 99
      memlock:
        soft: 102400
        hard: 102400
    environment:
      RMW_IMPLEMENTATION: ${RMW_IMPLEMENTATION:-rmw_cyclonedds_cpp}
      ROS_DOMAIN_ID: ${ROS_DOMAIN_ID:-0}
