#  Copyright (c) 2026 Franka Robotics GmbH	
#	
#  Licensed under the Apache License, Version 2.0 (the "License");	
#  you may not use this file except in compliance with the License.	
#  You may obtain a copy of the License at	
#	
#      http://www.apache.org/licenses/LICENSE-2.0	
#	
#  Unless required by applicable law or agreed to in writing, software	
#  distributed under the License is distributed on an "AS IS" BASIS,	
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.	
#  See the License for the specific language governing permissions and	
#  limitations under the License.

/**:
  controller_manager:
    ros__parameters:
      update_rate: 1000
      thread_priority: 98

      joint_follower_controller:
        type: franka_follower_controllers/JointFollowerController

      pid_joint_follower_controller:
        type: franka_follower_controllers/PIDJointFollowerController

      franka_robot_state_broadcaster:
        type: franka_robot_state_broadcaster/FrankaRobotStateBroadcaster
        state_interfaces:
          robot_state

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      move_to_position_controller:
        type: franka_example_controllers/MoveToStartExampleController

      gravity_compensation_controller:
        type: franka_example_controllers/GravityCompensationExampleController

  pid_joint_follower_controller:
    ros__parameters:
      p_gains:
        - 240.0
        - 240.0
        - 240.0
        - 240.0
        - 100.0
        - 60.0
        - 20.0
      d_gains:
        - 20.0
        - 20.0
        - 20.0
        - 10.0
        - 10.0
        - 10.0
        - 5.0
      i_gains:
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
      velocity_filter_alpha: 0.9  # Filters the velocity measured by the robot.
      velocity_limits_scaling: 0.9  # Scales the velocity limits by factor. Used to prevent joint velocity limits errors.
      acceleration_limits: [9.5, 9.5, 9.5, 9.5, 9.5, 9.5, 9.5]  # Acceleration limits for each joint (rad/s^2)
      torque_derivative_limits: [900.0, 900.0, 900.0, 900.0, 900.0, 900.0, 900.0]
      # HW torque limits: [87.0, 87.0, 87.0, 87.0, 12.0, 12.0, 12.0]
      torque_limits: [85.0, 85.0, 85.0, 85.0, 11.5, 11.5, 11.5]  # FR3 max torques per joint

      sync_complete_threshold: 0.01  # radians, threshold for considering the robot to be in sync with the target position
      sync_velocity_scaling: 0.2  # factor to scale velocity limits when not yet in sync

  joint_follower_controller:
    ros__parameters:
      robot_type: "fr3"
      k_alpha: 0.99
      k_gains:
        - 240.0
        - 240.0
        - 240.0
        - 240.0
        - 100.0
        - 60.0
        - 20.0
      d_gains:
        - 20.0
        - 20.0
        - 20.0
        - 10.0
        - 10.0
        - 10.0
        - 5.0

  move_to_position_controller:
    ros__parameters:
      k_gains:
        - 600.0
        - 600.0
        - 600.0
        - 600.0
        - 250.0
        - 150.0
        - 50.0
      d_gains:
        - 30.0
        - 30.0
        - 30.0
        - 30.0
        - 10.0
        - 10.0
        - 5.0

  gravity_compensation_controller:
    ros__parameters:
      robot_type: "fr3"

  franka_robot_state_broadcaster:
    ros__parameters:
      lock_try_count: 5 # Number of attempts to acquire the lock in a single on_update()
      lock_sleep_interval: 5 # microseconds sleep between attempts
      lock_log_error: false #  Log error if lock acquisition fails - false == do not log  
      lock_update_success: false # return update OK, although lock fails (no update occurs)

  joint_state_broadcaster:
    ros__parameters:
      robot_type: "fr3"
      joints:
        - fr3_joint1
        - fr3_joint2
        - fr3_joint3
        - fr3_joint4
        - fr3_joint5
        - fr3_joint6
        - fr3_joint7